"""empty message

Revision ID: 0f1a83c8e876
Revises: None
Create Date: 2015-12-21 22:55:42.434377

"""

# revision identifiers, used by Alembic.
revision = '0f1a83c8e876'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_timestamp'), 'tasks', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_timestamp'), table_name='tasks')
    op.drop_column('tasks', 'timestamp')
    ### end Alembic commands ###
